# Generated by Django 4.1 on 2022-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("module", models.CharField(max_length=100)),
                ("students", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
