# Generated by Django 4.1 on 2022-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
