# Generated by Django 4.1 on 2022-08-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="students",
            field=models.IntegerField(null=True),
        ),
    ]
